version: '3.9'
name: vite-docker
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: vite_docker_c
    ports:
      - '5173:5173'
    volumes:
      - ./:/app
      - /app/node_modules
